name: Deploy to Production

on:
  workflow_dispatch:  # Permite o acionamento manual para aprovar o deploy em produção

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com  # substitua pela URL real de produção

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Setting up environment for Production deploy"

      - name: Deploy to Production
        run: |
          ./scripts/deploy-gw-interno.sh
          ./scripts/deploy-gw-externo.sh
          ./scripts/deploy-domain.sh
          ./scripts/deploy-sandbox.sh
