name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://example.com # substitua pela URL real de produção

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Setting up environment for Production deploy"

      - name: Deploy to Production
        run: |
          ./scripts/deploy-gw-interno.sh
          ./scripts/deploy-gw-externo.sh
          ./scripts/deploy-domain.sh
          ./scripts/deploy-sandbox.sh
