name: Deploy to Development for Domain

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'configs/domain/**'         # Monitora apenas alterações na pasta domain

jobs:
  deploy:
    if: |
      contains(github.event.pull_request.labels.*.name, 'deploy-domain')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Setting up environment for Domain Development deploy"

      - name: Deploy to Development for Domain
        run: ./scripts/deploy-domain.sh
