name: Label Check

on:
  pull_request:
    types: [opened, synchronize]  # Aciona o workflow quando o PR é criado ou atualizado

jobs:
  check_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Faz o clone completo do repositório

      - name: Autenticar com o GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verificar se há uma palavra-chave obrigatória no corpo do PR
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Obtém o corpo do PR usando o GitHub CLI
          PR_BODY=$(gh pr view $PR_NUMBER --json body --jq '.body')

          # Define as palavras-chave obrigatórias
          REQUIRED_KEYWORDS=("deploy-gw-interno" "deploy-gw-externo" "deploy-domain" "deploy-sandbox")
          
          # Verifica se uma das palavras-chave obrigatórias está presente no corpo do PR
          KEYWORD_PRESENT=false
          for REQUIRED_KEYWORD in "${REQUIRED_KEYWORDS[@]}"; do
            if echo "$PR_BODY" | grep -iq "$REQUIRED_KEYWORD"; then
              KEYWORD_PRESENT=true
              echo "Palavra-chave '$REQUIRED_KEYWORD' encontrada no corpo do PR."
              break
            fi
          done

          # Falha se nenhuma palavra-chave obrigatória estiver presente
          if [ "$KEYWORD_PRESENT" = false ]; then
            echo "Erro: O corpo do PR requer uma das seguintes palavras-chave: ${REQUIRED_KEYWORDS[*]}"
            exit 1
          else
            echo "Palavra-chave obrigatória encontrada. PR pronto para revisão."
          fi
