name: Label Check

on:
  pull_request:
    types: [opened, synchronize]  # Aciona o workflow quando o PR é criado ou atualizado

jobs:
  check_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Faz o clone completo do repositório

      - name: Autenticar com o GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verificar se há uma label obrigatória no PR
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Obtém as labels do PR usando o GitHub CLI
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')

          # Define as labels obrigatórias
          REQUIRED_LABELS=("deploy-gw-interno" "deploy-gw-externo" "deploy-domain" "deploy-sandbox")
          
          # Verifica se uma das labels obrigatórias está presente
          LABEL_PRESENT=false
          for REQUIRED_LABEL in "${REQUIRED_LABELS[@]}"; do
            if echo "$LABELS" | grep -q "$REQUIRED_LABEL"; then
              LABEL_PRESENT=true
              break
            fi
          done

          # Falha se nenhuma label obrigatória estiver presente
          if [ "$LABEL_PRESENT" = false ]; then
            echo "Erro: Este PR requer uma das seguintes labels: ${REQUIRED_LABELS[*]}"
            exit 1
          else
            echo "Label obrigatória encontrada. PR pronto para revisão."
          fi
